apiVersion: batch/v1
kind: Job
metadata:
  namespace: kube-system
  name: px-hook-preinstall-cleanJobs
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-15"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: tiller
      restartPolicy: Never
      containers:
      - name: px-cleanJobs
        image: "lachlanevenson/k8s-kubectl:{{ template "px.kubernetesVersion" . }}"
        command: ['/bin/sh']
        args: ['-c','kubectl get jobs -nkube-system | grep px-hook | cut -f1 -d " " | xargs -r kubectl delete -nkube-system jobs']