apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-system
  name: px-predelete-cm
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-15"
data:
  px-delete-account-sa.yaml: |
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: px-delete-account
      namespace: kube-system
  px-delete-cr.yaml: |  
    kind: ClusterRole
    apiVersion: {{ template "rbac.apiVersion" . }}
    metadata:
      name: px-delete-nodelabel-role
    rules:
    - apiGroups: [""]
      resources: ["nodes"]
      verbs: ["watch", "get", "update", "list", "patch"]
  px-delete-crb.yaml: |
    kind: ClusterRoleBinding
    apiVersion: {{ template "rbac.apiVersion" . }}
    metadata:
      name: node-role-binding
    subjects:
    - kind: ServiceAccount
      name: px-delete-account
      namespace: kube-system
    roleRef:
      kind: ClusterRole
      name: px-delete-nodelabel-role
      apiGroup: rbac.authorization.k8s.io