apiVersion: batch/v1
kind: Job
metadata:
  namespace: kube-system
  name: px-predelete-hook
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 1
  template:
    spec:
      serviceAccountName: px-account
      restartPolicy: OnFailure
      containers:
      - name: post-delete-job
        image: "lachlanevenson/k8s-kubectl:{{ .Capabilities.KubeVersion.GitVersion }}"
        command:
        - sh
        - -c
        - "kubectl apply -f /etc/config"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        - name: kubectl
          mountPath: /kubectl
      volumes:
      - name: kubectl
        hostPath:
          path: /usr/bin/kubectl
      - name: config-volume
        configMap:
          name: px-predelete-cm